import { readFile, writeFile } from 'node:fs/promises'

const sourceUrl = new URL('../src/client.module.css', import.meta.url)
const outputUrl = new URL('../src/client-styles.generated.js', import.meta.url)
const source = await readFile(sourceUrl, 'utf8')
const names = [...new Set([...source.matchAll(/\.([A-Za-z_][\w-]*)/g)].map(match => match[1]))].sort()
const scoped = source.replace(/\.([A-Za-z_][\w-]*)/g, (_match, name) => `.rp-reply-options-${name}`)
const mapping = Object.fromEntries(names.map(name => [name, `rp-reply-options-${name}`]))
const moduleText = `// Generated by scripts/generate-styles.mjs; do not edit by hand.\nexport const css = ${JSON.stringify(mapping, null, 2)}\nconst STYLE_ID = 'dsh-roleplay-rp-reply-options-styles'\nconst STYLE_OWNER = 'dsh-roleplay-rp-reply-options'\nconst STYLE_TEXT = ${JSON.stringify(scoped)}\nexport function ensureStyles() {\n  document.getElementById(STYLE_ID)?.remove()\n  const style = document.createElement('style')\n  style.id = STYLE_ID\n  style.dataset.plugin = STYLE_OWNER\n  style.textContent = STYLE_TEXT\n  document.head.append(style)\n  return () => style.remove()\n}\n`
await writeFile(outputUrl, moduleText, 'utf8')
