/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RoleplayRemotePayload, RoleplayTransportResponse } from 'dsh-roleplay-rp-remote/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$726f6c65706c6179 {
    assets: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    characterCards: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    features: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    loreBooks: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    messageActions: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    personas: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    presets: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    quickReplies: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    subagents: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    writingStyles: (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
  }
  interface TypertRemoteMap {
    'roleplay/assets': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/characterCards': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/features': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/loreBooks': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/messageActions': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/personas': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/presets': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/quickReplies': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/subagents': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
    'roleplay/writingStyles': (endpoint: string, payload: RoleplayRemotePayload, signal?: AbortSignal) => Promise<RemoteResult<RoleplayTransportResponse>>
  }
  interface TypertRemoteNamespaceMap {
    'roleplay': TypertRemoteNamespace$726f6c65706c6179
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
