import { readFile, writeFile } from 'node:fs/promises'

const sourceUrl = new URL('../src/client.module.css', import.meta.url)
const outputUrl = new URL('../src/client-styles.generated.js', import.meta.url)
const source = await readFile(sourceUrl, 'utf8')

function scopeClassNames(cssText) {
  const names = new Set()
  let scoped = ''
  let cursor = 0
  while (cursor < cssText.length) {
    if (cssText.startsWith('/*', cursor)) {
      const close = cssText.indexOf('*/', cursor + 2)
      const end = close === -1 ? cssText.length : close + 2
      scoped += cssText.slice(cursor, end)
      cursor = end
      continue
    }
    const char = cssText[cursor]
    if (char === '"' || char === "'") {
      let end = cursor + 1
      while (end < cssText.length) {
        if (cssText[end] === '\\') end += 2
        else if (cssText[end] === char) { end += 1; break }
        else end += 1
      }
      scoped += cssText.slice(cursor, end)
      cursor = end
      continue
    }
    if (char === '.' && /[A-Za-z_]/.test(cssText[cursor + 1] ?? '')) {
      let end = cursor + 2
      while (/[\w-]/.test(cssText[end] ?? '')) end += 1
      const name = cssText.slice(cursor + 1, end)
      names.add(name)
      scoped += `.rp-message-actions-${name}`
      cursor = end
      continue
    }
    scoped += char
    cursor += 1
  }
  return { names: [...names].sort(), scoped }
}

const { names, scoped } = scopeClassNames(source)
const mapping = Object.fromEntries(names.map(name => [name, `rp-message-actions-${name}`]))
const moduleText = `// Generated by scripts/generate-styles.mjs; do not edit by hand.\nexport const css = ${JSON.stringify(mapping, null, 2)}\nconst STYLE_ID = 'dsh-roleplay-rp-message-actions-styles'\nconst STYLE_OWNER = 'dsh-roleplay-rp-message-actions'\nconst STYLE_TEXT = ${JSON.stringify(scoped)}\nexport function ensureStyles() {\n  document.getElementById(STYLE_ID)?.remove()\n  const style = document.createElement('style')\n  style.id = STYLE_ID\n  style.dataset.plugin = STYLE_OWNER\n  style.textContent = STYLE_TEXT\n  document.head.append(style)\n  return () => style.remove()\n}\n`
await writeFile(outputUrl, moduleText, 'utf8')
