import { readFile, writeFile } from 'node:fs/promises'

const source = (await Promise.all([
  new URL('../src/client.module.css', import.meta.url),
  new URL('../src/client-availability.module.css', import.meta.url),
].map(url => readFile(url, 'utf8')))).join('\n')
const names = [...new Set([...source.matchAll(/\.([A-Za-z_][\w-]*)/g)].map(match => match[1]))].sort()
const scoped = source.replace(/\.([A-Za-z_][\w-]*)/g, (_match, name) => `.rp-subagent-manager-${name}`)
const mapping = Object.fromEntries(names.map(name => [name, `rp-subagent-manager-${name}`]))
const output = `// Generated by scripts/generate-styles.mjs; do not edit by hand.\nexport const css = ${JSON.stringify(mapping, null, 2)}\nconst STYLE_ID = 'dsh-roleplay-rp-subagent-manager-styles'\nconst STYLE_OWNER = 'dsh-roleplay-rp-subagent-manager'\nconst STYLE_TEXT = ${JSON.stringify(scoped)}\nexport function ensureStyles() {\n  document.getElementById(STYLE_ID)?.remove()\n  const style = document.createElement('style')\n  style.id = STYLE_ID\n  style.dataset.plugin = STYLE_OWNER\n  style.textContent = STYLE_TEXT\n  document.head.append(style)\n  return () => style.remove()\n}\n`
await writeFile(new URL('../src/client-styles.generated.js', import.meta.url), output, 'utf8')
